config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp.views.menu.menu import Menu
from myapp.views.customer.search import CustomerSearch
from myapp.views.customer.register import CustomerRegister

app_name = 'myapp'

urlpatterns = [
    path('', Menu.as_view(), name='menu'),
    path('customers/search', CustomerSearch.as_view()  , name='customers_search'),
    path('customers/input' , CustomerRegister.as_view(), name='customers_input' ),
]

myapp/models/customer.py
from django.db import models

class Customer(models.Model):
    class Meta:
        db_table_comment = "顧客マスタ"

    id   = models.AutoField (db_comment='ID', primary_key=True)
    mail = models.EmailField(db_comment='メールアドレス', unique=True, max_length=50 , blank = False, null = False)
    name = models.CharField (db_comment='会社名', max_length=50 , blank = False, null = False)
    post = models.CharField (db_comment='郵便番号', max_length=10, blank = False, null = False )
    addr = models.CharField (db_comment='住所', max_length=200, blank = True , null = True )
    tel  = models.CharField (db_comment='TEL', max_length=20 , blank = False, null = False)
    fax  = models.CharField (db_comment='FAX', max_length=20 , blank = True , null = True )
    note = models.TextField (db_comment='備考', blank = True , null = True )
    public_flag = models.BooleanField(db_comment='公開フラグ', default = False)
    delete_flag = models.BooleanField(db_comment='削除フラグ', default = False)
    created_at = models.DateTimeField(db_comment='作成日', auto_now=True)
    updated_at = models.DateTimeField(db_comment='更新日', auto_now_add=True)

    def __str__(self):
        return self.name

myapp/templates/base.html
{% load adminlte_helpers i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}
    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}
    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
        {% block style_sheets %}{% endblock %}
    {% endblock %}
    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}layout-fixed {% endblock %}{% endblock %}">
{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'header.html' %}
        {% endblock %}
        {% block nav_sidebar %}
            {% include 'sidebar.html' %}
        {% endblock %}
        {% block content_wrapper %}

        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}

        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}
    </div>
{% endblock body %}
{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
{% block js %}{% endblock %}
{% endblock %}
{% block extra_js %}{% endblock %}
{% block extra_foot %}{% endblock %}
</body>
</html>

myapp/templates/commons/formcheckbox.html
{% load widget_tweaks %}
 <div style="margin: -40px 0 0 0px;" class="form-switch">
{{form|add_class:"form-check-input"|attr:"role:switch"}}
</div>
{% for err in form.errors %}
<span class="badge badge-danger">{{ err }}</span>
{% endfor %}

myapp/templates/commons/forminput.html
{% load widget_tweaks %}
{{form|add_class:"form-control"}}
{% for err in form.errors %}
<span class="badge badge-danger">{{ err }}</span>
{% endfor %}

myapp/templates/commons/formtextarea.html
{% load widget_tweaks %}
{{form|add_class:"form-control"|attr:cols|attr:rows}}
{% for err in form.errors %}
<span class="badge badge-danger">{{ err }}</span>
{% endfor %}

myapp/templates/commons/pagecount.html
<h5>{{page_obj.paginator.count}} 件中 {{page_obj.start_index}} 件から {{page_obj.end_index}} 件を表示</h5>

myapp/templates/commons/paginator.html
<nav aria-label="Page navigation">
    <ul class="pagination text-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">前へ</span>
            </a>
        </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="javascript:void(0)" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">前へ</span>
                </a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">次へ</span>
                </a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="javascript:void(0)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">次へ</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

myapp/templates/commons/toast.html
<div aria-live="polite" aria-atomic="true" style="position: relative;">
    <div style="position: absolute;">
    {% if   info.type == 1%}
        <div role="alert" aria-live="assertive" aria-atomic="true" class="toast bg-success" data-autohide="false">
    {% elif info.type == 9%}
        <div role="alert" aria-live="assertive" aria-atomic="true" class="toast bg-danger" data-autohide="false">
    {% endif %}
            <div style="text-align: center;" class="toast-body">{{info.message}}</div>
        </div>
    </div>
</div>

<script>
    $(window).on('load', function (){
        //処理
        $('.toast').toast({animation:true, autohide: true, delay:1000});
        $(".toast").toast("show");
    });
</script>

myapp/templates/customer/register.html
{% extends '../base.html' %}

{% block content %}
{% include "../commons/toast.html" with info=info %}

<div class="container my-1">
    <h2 class="text-center py-2">顧客マスタ登録</h2>
</div>

<form action="{% url 'myapp:customers_input' %}" method="POST" novalidate>
    {% csrf_token %}
    <table class="table-sm" width="50%" style="margin-left:auto; margin-right: auto;">
        <tr>
            <td width="15%"><label for="InputName">{{ form.mail.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.mail %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.name.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.name %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.post.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.post %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.addr.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.addr %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.tel.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.tel %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.fax.label }}</label></td>
            <td>{% include "../commons/forminput.html" with form=form.fax %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.note.label }}</label></td>
            <td>{% include "../commons/formtextarea.html" with form=form.note cols="cols:40" rows="rows:5" %}</td>
        </tr>
        <tr>
            <td><label for="InputName">{{ form.public_flag.label }}</label></td>
            <td>{% include "../commons/formcheckbox.html" with form=form.public_flag role="role:switch"%}</td>
        </tr>
        <tr>
            <td><button type="submit" class="btn btn-primary">登録</button></td>
            <td></td>
        </tr>
    </table>
</form>
{% endblock %}

myapp/templates/customer/search.html
{% extends '../base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container my-1">
    <h2 class="text-center py-2">顧客マスタ検索</h2>
</div>
<form id="search-form" action="{% url 'myapp:customers_search' %}" method="GET">
    {% csrf_token %}
    <p class="h5">検索条件</p>
    <table class="table table-sm table-info" width="100%">
        <tr>
            <td width="15%">
                <label for="InputName">顧客名</label>
                {% include "../commons/forminput.html" with form=form.name %}
            </td>
            <td width="5%"></td>
            <td width="15%">
                <label for="InputName">メールアドレス</label>
                {% include "../commons/forminput.html" with form=form.mail %}
            </td>
            <td width="5%"></td>
            <td width="40%">
                <label for="InputName">住所</label>
                {% include "../commons/forminput.html" with form=form.addr %}
            </td>
            <td width="5%"></td>
            <td width="15%">
                <label for="InputName">電話番号</label>
                {% include "../commons/forminput.html" with form=form.tel %}
            </td>
        </tr>
        <tr>
            <td colspan="7">
                <button type="submit" class="btn btn-primary">検索</button>
            </td>
        </tr>
    </table>
</form>
<br>

<table width="100%">
    <tr>
        <td width="80%"><p class="h5">検索一覧</p></td>
        <td width="15%">{% include "../commons/pagecount.html" %}</td>
        <td width="5%">{% include "../commons/paginator.html" %}</td>
    </tr>
</table>

<table width="100%" class="table table-sm table-striped table-hover table_sticky">
    <thead>
        <tr class="table-primary">
            <th width="2%">ID</th>
            <th width="10%">会社名</th>
            <th width="10%">メールアドレス</th>
            <th width="5%">郵便番号</th>
            <th>住所</th>
            <th width="8%">TEL</th>
            <th width="8%">FAX</th>
            <th>公開/非公開</th>
            <th width="10%">作成日</th>
            <th width="10%">更新日</th>
        </tr>
    </thead>
    <tbody>
    {% for customer in object_list %}
        <tr>
            <td>{{ customer.id }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.mail }}</td>
            <td>{{ customer.post }}</td>
            <td>{{ customer.addr }}</td>
            <td>{{ customer.tel }}</td>
            <td>{{ customer.fax }}</td>
            {% if customer.public_flag %}
                <td><span class="badge badge-success">公開中</span></td>
            {% else %}
                <td><span class="badge badge-secondary">非公開</span></td>
            {% endif %}
            <td>{{ customer.created_at }}</td>
            <td>{{ customer.updated_at }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

myapp/templates/header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Admin</a>
        </li>
    </ul>
</nav>

myapp/templates/menu.html
{% extends "base.html" %}

myapp/templates/sidebar.html
{% load adminlte_helpers %}
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="/" class="brand-link">
        <img src="{%static 'images/sakura.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Python Django</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">{% block nav_heading %}メニュー{% endblock %}</li>
                <li class="nav-item has-tree-view ">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-object-group"></i>
                        <p>顧客マスタ</p>
                        <p><i class="right fas fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview menu-open">
                        <li class="nav-item">
                            <a href="{% url 'myapp:customers_search' %}" class="nav-link"><i class="nav-icon fas fa-circle"></i>検索</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'myapp:customers_input' %}" class="nav-link"><i class="nav-icon fas fa-circle"></i>新規登録</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>